### DISCUSSION TITLE
New enjinn.yaml format

### DISCUSSION THREAD

**Discussion by shayded-exe** [rshea0/enjinn#40] [Ideas]
I'm considering ways to improve the format.

Here's one possibility:

```yaml
smartPlaylists:
  - name: Current
    rules:
      and:
        - field: artist
          operator: contains
          value: test
        - field: title
          operator: contains
          value: remix
        - field: bpm
          operator: '>='
          value: 128

  - name: New
    rules:
      and:
        - [artist, contains, test]
        - [title, contains, remix, { caseSensitive: true }]
        - [bpm, '>=', 128]
```
