### ISSUE TITLE
Simplified smart playlist rule definition

### ISSUE THREAD

**Issue by rshea0** [rshea0/enjinn#43]
### Current

```yaml
rules:
  and:
    - field: artist
      operator: contains
      value: test
    - field: title
      operator: contains
      value: remix
      caseSensitive: true
    - field: bpm
      operator: '>='
      value: 128
```

### New

```yaml
rules:
  and:
    - [artist, contains, test]
    - [title, contains, remix, { caseSensitive: true }]
    - [bpm, '>=', 128]
```

_Originally posted by @rshea0 in https://github.com/rshea0/enjinn/discussions/40_
